site_name: Polaroids
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: "numpy"
nav:
  - Home: index.md
  - API Reference: api.md
